BUILD instructions
==================

vasp_unfold is actually just a collection of Python
source files. They can be bundled together into an
executable archive by running the build.sh script.
Once vasp_unfold is generated by build sript, it can
be run independently and you can place it wherever
it fits you best to use it.

If Python is invoked in a non-standard way on your
system, please change the PYTHON_COMMAND variable
in build.sh script.
